apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: htmlapp
  template:
    metadata:
      labels:
        app: htmlapp
    spec:
      containers:
      - image: srinivasarao2468/htmlapp:tagVersion
        name: htmlapp
        ports:
        - containerPort: 80
